# Set this website's info
# Change "coffeebank" to your GitHub username
# Change "moonrise" to your repository name
url: "https://serverkur.github.io"
baseurl: "/serverkur-en"
siteIcon: /media/android-chrome-192x192.png
siteYear: 2022
siteFooterlink: /about
showinSearchEngines: true
# googleAnalyticsID: (uncomment to use)


# Set basic server info
serverName: ServerKUR | Hosting
serverDescription: Free Game Hosting - Get started now with 1GB RAM, unlimited players, unlimited plugins, 24/7 up, no queues! Support for Minecraft, Discord Bots and more!
serverIP: Create Server
useBedrockForOnlineStatus: false
clientpanel: https://en.serverkur.net


# Discord information
discordInvite: https://discord.gg/P6T3F9nTzn
discordServerID: 914409464159928341
discordChannelID: 962288046944960542


# # Navbar Links at the top of the page (uncomment "siteNav" to use)
# #   name - The title on the navbar
# #   url - The link it should go to (for example, if you have "maps.md" file, put "maps")
# #   newtab - Whether link should open in new tab
# 
# siteNav:
#   - name: Client Panel
#     url: client
#     newtab: true
#   - name: About Us
#     url: about
#   - name: Game Panel
#     url: panel


# Don't change anything below here, these are defaults set by GitHub Pages:
# ======
theme: minima
# plugins:
#   - jekyll-feed
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
